# Generated by Django 5.0.2 on 2025-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_emirates_id_alter_user_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
